# Request to get all available currencies
GET http://localhost:5116/api/v1/currencies

###

# Request to create a new payment request
POST http://localhost:5116/api/v1/payments/BTC/100000000

###

# Request to get a specific payment request by ID
GET http://localhost:5116/api/v1/payments/16f793c0-403d-4724-9ddf-936c1543b9be